from mesa import Agent
from enum import Enum
import random


# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0
        self.condition = condition


    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)


# ---------------------------------------------------------------
class Bridge(Infra):
    """
    Creates delay time

    Attributes
    __________
    condition:
        condition of the bridge

    delay_time: int
        the delay (in ticks) caused by this bridge
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown'):
        super().__init__(unique_id, model, length, name, road_name, condition)


        print(f"Bridge condition: {self.condition}")
        self.condition = condition
        self.length = length
        self.name = name
        self.road_name = road_name

        # Assign breakdown probability based on bridge condition (A, B, C, D)
        self.breakdown_prob = model.breakdown_probs.get(self.condition, 0)
        #print(f"Bridge Condition: {self.condition}, Breakdown Probability: {self.breakdown_prob}")

        self.broken = False
        self.delay_time = 0  # Default to no delay

        # Determine if bridge breaks down based on probability
        if random.random() < self.breakdown_prob:
            self.broken = True
            self.assign_delay()

        print(self.delay_time)  # Debugging Output

    def assign_delay(self):
        """Assign delay time based on bridge length if broken"""
        if self.length > 200:
            self.delay_time = random.triangular(1, 2, 4) * 60  # Convert hours to minutes
        elif 50 < self.length <= 200:
            self.delay_time = random.uniform(45, 90)
        elif 10 < self.length <= 50:
            self.delay_time = random.uniform(15, 60)
        else:
            self.delay_time = random.uniform(10, 20)

    def get_delay(self):
        """Return the delay time if the bridge is broken, otherwise return 0"""
        return self.delay_time if self.broken else 0

    def get_delay_time(self):
        """Alias for get_delay()"""
        return self.get_delay()


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False

    def remove(self, vehicle):
        self.model.schedule.remove(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------

class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    generation_frequency = 5
    vehicle_generated_flag = False

    def step(self):
        if self.model.schedule.steps % self.generation_frequency == 0:
            self.generate_truck()
        else:
            self.vehicle_generated_flag = False

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if agent:
                self.model.schedule.add(agent)
                agent.set_path()
                Source.truck_counter += 1
                self.vehicle_count += 1
                self.vehicle_generated_flag = True
                print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """
    Represents a vehicle moving through the infrastructure.
    """

    speed = 50 * 1000 / 60  # Speed in meters per minute
    step_time = 1  # One tick represents 1 minute

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.waited_at = None
        self.removed_at_step = None

    def __str__(self):
        return f"Vehicle{self.unique_id} +{self.generated_at_step} -{self.removed_at_step} {self.state}({self.waiting_time}) {self.location}({self.location.vehicle_count}) {self.location_offset}"

    def set_path(self):
        """
        Set the origin-destination path of the vehicle.
        """
        self.path_ids = self.model.get_random_route(self.generated_by.unique_id)

    def step(self):
        """
        Vehicle waits or drives at each step.
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        print(self)

    def drive(self):
        """
        Moves the vehicle forward in its path.
        """
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            self.drive_to_next(distance_rest)
        else:
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        Moves the vehicle to the next infrastructure component.
        """
        self.location_index += 1
        next_id = self.path_ids[self.location_index]
        next_infra = self.model.schedule._agents[next_id]

        if isinstance(next_infra, Sink):
            self.arrive_at_next(next_infra, 0)
            self.removed_at_step = self.model.schedule.steps
            self.model.travel_time.append(self.removed_at_step - self.generated_at_step)
            self.location.remove(self)
            return

        elif isinstance(next_infra, Bridge):
            self.waiting_time = next_infra.get_delay_time()
            if self.waiting_time > 0:
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT
                return

        if next_infra.length > distance:
            self.arrive_at_next(next_infra, distance)
        else:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset.
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

# EOF -----------------------------------------------------------


